- translations/ui-circulation-log/ar.json
- translations/ui-circulation-log/ca.json
- translations/ui-circulation-log/da.json
- translations/ui-circulation-log/de.json
- translations/ui-circulation-log/en_GB.json
- translations/ui-circulation-log/en_SE.json
- translations/ui-circulation-log/en_US.json
- translations/ui-circulation-log/es.json
- translations/ui-circulation-log/es_419.json
- translations/ui-circulation-log/es_ES.json
- translations/ui-circulation-log/fr.json
- translations/ui-circulation-log/fr_FR.json
- translations/ui-circulation-log/he.json
- translations/ui-circulation-log/hu.json
- translations/ui-circulation-log/it_IT.json
- translations/ui-circulation-log/ja.json
- translations/ui-circulation-log/pt_BR.json
- translations/ui-circulation-log/pt_PT.json
- translations/ui-circulation-log/ru.json
- translations/ui-circulation-log/ur.json
- translations/ui-circulation-log/zh_CN.json
- translations/ui-circulation-log/zh_TW.json
> Update translation strings as of 20200811T193833

- translations/ui-circulation-log/ar.json
- translations/ui-circulation-log/fr_FR.json
- translations/ui-circulation-log/pt_BR.json
> Update translation strings as of 20200813T135432

- CHANGELOG.md
- src/CirculationLog.js
- src/CirculationLogList/CirculationLogEventActions/CirculationLogEventActions.js
- src/CirculationLogList/CirculationLogEventActions/index.js
- src/CirculationLogList/CirculationLogList.js
- src/CirculationLogList/CirculationLogListContainer.js
- src/CirculationLogList/CirculationLogListFilter/CirculationLogListFilter.js
- src/CirculationLogList/CirculationLogListFilter/index.js
- src/CirculationLogList/index.js
- translations/ui-circulation-log/en.json
https://issues.folio.org/browse/UICIRCLOG-3 …
> UICIRCLOG-3 View circulation log table

- translations/ui-circulation-log/ar.json
- translations/ui-circulation-log/ca.json
- translations/ui-circulation-log/da.json
- translations/ui-circulation-log/de.json
- translations/ui-circulation-log/en_GB.json
- translations/ui-circulation-log/en_SE.json
- translations/ui-circulation-log/en_US.json
- translations/ui-circulation-log/es.json
- translations/ui-circulation-log/es_419.json
- translations/ui-circulation-log/es_ES.json
- translations/ui-circulation-log/fr.json
- translations/ui-circulation-log/fr_FR.json
- translations/ui-circulation-log/he.json
- translations/ui-circulation-log/hu.json
- translations/ui-circulation-log/it_IT.json
- translations/ui-circulation-log/ja.json
- translations/ui-circulation-log/pt_BR.json
- translations/ui-circulation-log/pt_PT.json
- translations/ui-circulation-log/ru.json
- translations/ui-circulation-log/ur.json
- translations/ui-circulation-log/zh_CN.json
- translations/ui-circulation-log/zh_TW.json
> Update translation strings as of 20200817T131718

- CHANGELOG.md
- package.json
- translations/ui-circulation-log/en.json
https://issues.folio.org/browse/UICIRCLOG-13 …
> UICIRCLOG-13 Circulation log permissions

- translations/ui-circulation-log/ar.json
- translations/ui-circulation-log/pt_BR.json
- translations/ui-circulation-log/zh_CN.json
> Update translation strings as of 20200824T140725

- translations/ui-circulation-log/it_IT.json
> Update translation strings as of 20200827T215834

- CHANGELOG.md
- src/CirculationLogList/CirculationLogEventActions/CirculationLogEventActions.js
- src/CirculationLogList/CirculationLogEventActions/utils.js
- src/CirculationLogList/CirculationLogList.js
- translations/ui-circulation-log/en.json
https://issues.folio.org/browse/UICIRCLOG-12 …
> UICIRCLOG-12 Circulation log ellipses pop up box

- CHANGELOG.md
- src/CirculationLogList/CirculationLogEventActions/utils.js
https://issues.folio.org/browse/UICIRCLOG-16 …
> UICIRCLOG-16 Ellipses pop up for Manual Blocks

- CHANGELOG.md
- src/CirculationLogList/CirculationLogEventActions/CirculationLogEventActions.js
- src/CirculationLogList/CirculationLogEventActions/CirculationLogEventActions.test.js
https://issues.folio.org/browse/UICIRCLOG-18 …
> UICIRCLOG-18 Ellipses menu option permissions

- CHANGELOG.md
- src/CirculationLogList/CirculationLogList.js
- translations/ui-circulation-log/en.json
https://issues.folio.org/browse/UICIRCLOG-19 …
> UICIRCLOG-19 Update circulation log table headings

- CHANGELOG.md
- src/CirculationLogList/CirculationLogListContainer.js
- src/CirculationLogList/CirculationLogListFilter/CirculationLogListFilter.js
https://issues.folio.org/browse/UICIRCLOG-20 …
> UICIRCLOG-20 Switch service point filter from checkboxes to multi-select picker

- translations/ui-circulation-log/en.json
https://issues.folio.org/browse/UICIRCLOG-19 …
> UICIRCLOG-19 fix translations

- src/CirculationLogList/CirculationLogEventActions/CirculationLogEventActions.js
- src/CirculationLogList/CirculationLogEventActions/CirculationLogEventActions.test.js
- src/CirculationLogList/CirculationLogList.js
- src/CirculationLogList/CirculationLogList.test.js
https://issues.folio.org/browse/UICIRCLOG-21 …
> UICIRCLOG-21 fix item related info

- src/CirculationLogList/CirculationLogEventActions/utils.js
- src/CirculationLogList/CirculationLogEventActions/utils.test.js
https://issues.folio.org/browse/UICIRCLOG-18 …
> UICIRCLOG-18 fix: item details action should be available for request events

- translations/ui-circulation-log/fr_FR.json
> Update translation strings as of 20201005T202004

- CHANGELOG.md
- jest.config.js
- src/CirculationLogList/CirculationLogEventActions/CirculationLogEventActions.js
- src/CirculationLogList/CirculationLogEventActions/CirculationLogEventActions.test.js
- src/CirculationLogList/CirculationLogEventActions/utils.js
- src/CirculationLogList/CirculationLogEventActions/utils.test.js
- src/CirculationLogList/CirculationLogEventItems/CirculationLogEventItem.js
- src/CirculationLogList/CirculationLogEventItems/CirculationLogEventItem.test.js
- src/CirculationLogList/CirculationLogEventItems/CirculationLogEventItems.css
- src/CirculationLogList/CirculationLogEventItems/CirculationLogEventItems.js
- src/CirculationLogList/CirculationLogEventItems/CirculationLogEventItems.test.js
- src/CirculationLogList/CirculationLogEventItems/index.js
- src/CirculationLogList/CirculationLogList.js
- src/CirculationLogList/constants.js
- translations/ui-circulation-log/en.json
https://issues.folio.org/browse/UICIRCLOG-21 …
> UICIRCLOG-21 Show items for multiple-item notice in circulation log

- src/CirculationLogList/constants.js
- translations/ui-circulation-log/en.json
While it's helpful for reviewers to help identify potential problems, ensuring that it's …
> add missed object translation

- translations/ui-circulation-log/ar.json
- translations/ui-circulation-log/ca.json
- translations/ui-circulation-log/da.json
- translations/ui-circulation-log/de.json
- translations/ui-circulation-log/en_GB.json
- translations/ui-circulation-log/en_SE.json
- translations/ui-circulation-log/en_US.json
- translations/ui-circulation-log/es.json
- translations/ui-circulation-log/es_419.json
- translations/ui-circulation-log/es_ES.json
- translations/ui-circulation-log/fr.json
- translations/ui-circulation-log/fr_FR.json
- translations/ui-circulation-log/he.json
- translations/ui-circulation-log/hi_IN.json
- translations/ui-circulation-log/hu.json
- translations/ui-circulation-log/it_IT.json
- translations/ui-circulation-log/ja.json
- translations/ui-circulation-log/ko.json
- translations/ui-circulation-log/pl.json
- translations/ui-circulation-log/pt_BR.json
- translations/ui-circulation-log/pt_PT.json
- translations/ui-circulation-log/ru.json
- translations/ui-circulation-log/ur.json
- translations/ui-circulation-log/zh_CN.json
- translations/ui-circulation-log/zh_TW.json
> Update translation strings as of 20201013T203429

- src/CirculationLogList/CirculationLogListContainer.js
While it's helpful for reviewers to help identify potential problems, ensuring that it's …
> UICIRCLOG-4 fix pagination

- translations/ui-circulation-log/es.json
- translations/ui-circulation-log/es_419.json
- translations/ui-circulation-log/es_ES.json
> Update translation strings as of 20201016T144229

- translations/ui-circulation-log/es.json
- translations/ui-circulation-log/es_419.json
- translations/ui-circulation-log/es_ES.json
> Update translation strings as of 20201102T140138

- translations/ui-circulation-log/ja.json
- translations/ui-circulation-log/ko.json
> Update translation strings as of 20201105T151643

- CHANGELOG.md
- package.json
- src/CirculationLogList/CirculationLogList.js
- src/CirculationLogList/CirculationLogListFilter/CirculationLogListFilter.js
- src/CirculationLogList/CirculationLogListFilter/CirculationLogListFilter.test.js
- src/CirculationLogList/CirculationLogListFilter/TextFilters/Field.js
- src/CirculationLogList/CirculationLogListFilter/TextFilters/TextFilters.js
- src/CirculationLogList/CirculationLogListFilter/TextFilters/index.js
- src/hooks/index.js
- src/hooks/useLocationFilters.js
- src/hooks/useT.js
- translations/ui-circulation-log/en.json
UICIRCLOG-34
While it's helpful for reviewers to help identify potential problems, ensuring …
> UICIRCLOG-34 Make text filters submit on a button or Enter

- CHANGELOG.md
- src/CirculationLogList/constants.js
UICIRCLOG-30 add 'Checked in' loan filter
To add a filter to Loan actions called Checked in  …
> UICIRCLOG-30 add 'Checked in' loan filter

- CHANGELOG.md
- package.json
https://issues.folio.org/browse/UICIRCLOG-46 …
> UICIRCLOG-46 Update `@folio/stripes-cli` to `v2`

- CHANGELOG.md
- PERSONAL_DATA_DISCLOSURE.md
https://issues.folio.org/browse/UICIRCLOG-36 …
> UICIRCLOG-36 Add personal data disclosure form

- CHANGELOG.md
- jest.config.js
- package.json
- src/CirculationLogList/CirculationLogList.js
- src/CirculationLogList/CirculationLogList.test.js
- src/CirculationLogList/CirculationLogListActions/CirculationLogListActions.js
- src/CirculationLogList/CirculationLogListActions/CirculationLogListActions.test.js
- src/CirculationLogList/CirculationLogListActions/index.js
- src/CirculationLogList/CirculationLogListActions/useCirculationLogExport.js
- src/CirculationLogList/CirculationLogListActions/useCirculationLogExport.test.js
- translations/ui-circulation-log/en.json
https://issues.folio.org/browse/UICIRCLOG-22 …
> UICIRCLOG-22 Circulation log Action dropdown - Exporting Data

- src/CirculationLogList/CirculationLogListActions/useCirculationLogExport.js
https://issues.folio.org/browse/UICIRCLOG-22 …
> UICIRCLOG-22 increase polling interval

- CHANGELOG.md
- package.json
- src/CirculationLogList/CirculationLogListActions/useCirculationLogExport.js
- src/CirculationLogList/CirculationLogListFilter/CirculationLogListFilter.js
Release v1.0.2
While it's helpful for reviewers to help identify potential problems, …
> Release v1.1.0

- CHANGELOG.md
- translations/ui-circulation-log/en.json
https://issues.folio.org/browse/UICIRCLOG-51 …
> UICIRCLOG-51 Add support for circ action "Created through override"

- CHANGELOG.md
- src/CirculationLogList/CirculationLogEventActions/CirculationLogEventActions.js
- src/CirculationLogList/CirculationLogEventActions/utils.js
- src/CirculationLogList/CirculationLogEventActions/utils.test.js
While it's helpful for reviewers to help identify potential problems, ensuring that it's …
> UICIRCLOG-59 Do not show links to Loan details if user ID is `undefined`

- package.json
- src/CirculationLogList/CirculationLogEventActions/CirculationLogEventActions.test.js
Add integration tests for https://issues.folio.org/browse/UICIRCLOG-59
Refactor the tests for actions.
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies …
> UICIRCLOG-59 Refactor test for actions

- CHANGELOG.md
- translations/ui-circulation-log/en.json
https://issues.folio.org/browse/UICIRCLOG-39 …
> UICIRCLOG-39 Update anonymize filter in Circulation log

- CHANGELOG.md
- package.json
- src/CirculationLogList/CirculationLogListFilter/TextFilters/TextFilters.js
- src/CirculationLogList/CirculationLogListFilter/TextFilters/TextFilters.test.js
- translations/ui-circulation-log/en.json
https://issues.folio.org/browse/UICIRCLOG-42 …
> UICIRCLOG-42 Add patron look-up in filters

- CHANGELOG.md
- Jenkinsfile
- package.json
https://issues.folio.org/browse/UICIRCLOG-64 …
> UICIRCLOG-64 Compile Translation Files into AST Format

- CHANGELOG.md
- src/CirculationLogList/CirculationLogListFilter/TextFilters/TextFilters.js
- src/CirculationLogList/CirculationLogListFilter/TextFilters/TextFilters.test.js
https://issues.folio.org/browse/UICIRCLOG-65 …
> UICIRCLOG-65 Focus the "User barcode" field after "Patron lookup"

- CHANGELOG.md
- translations/ui-circulation-log/en.json
https://issues.folio.org/browse/UICIRCLOG-70 …
> UICIRCLOG-70 Add support for log records with new Circ action: "Send error"

- .eslintrc
- CHANGELOG.md
- package.json
- src/CirculationLogList/CirculationLogList.js
- src/CirculationLogList/CirculationLogList.test.js
- src/CirculationLogList/CirculationLogListContainer.js
- src/CirculationLogList/CirculationLogListContainer.test.js
- src/CirculationLogList/CirculationLogListFilter/CirculationLogListFilter.js
- src/CirculationLogList/CirculationLogListFilter/CirculationLogListFilter.test.js
- src/CirculationLogList/CirculationLogListFilter/TextFilters/TextFilters.js
https://issues.folio.org/browse/UICIRCLOG-54 …
> UICIRCLOG-54 DateRangeFilter focus update

- CHANGELOG.md
- src/CirculationLogList/CirculationLogListFilter/CirculationLogListFilter.js
https://issues.folio.org/browse/UICIRCLOG-73 …
> UICIRCLOG-73: DateRange filter focus blocks opening of Accordion components

- translations/ui-circulation-log/en.json
https://issues.folio.org/browse/UICIRCLOG-72 …
> UICIRCLOG-72 Edit success toast language in Circulation log export

- CHANGELOG.md
- translations/ui-circulation-log/es.json
https://issues.folio.org/browse/UICIRCLOG-85 …
> UICIRCLOG-85 Change "Age" to lost to "Aged" to lost

- CHANGELOG.md
- src/CirculationLogList/FormattedTime.js
While it's helpful for reviewers to help identify potential problems, ensuring that it's …
> UICIRCLOG-92 Circulation log showing UTC time instead of local time for loans/requests/fee-fines

- CHANGELOG.md
- package.json
https://issues.folio.org/browse/UICIRCLOG-98 …
> UICIRCLOG-98 replace babel-eslint with @babel/eslint-parser

- CHANGELOG.md
- package.json
- src/CirculationLogList/CirculationLogList.js
- src/CirculationLogList/CirculationLogListActions/CirculationLogListActions.js
https://issues.folio.org/browse/UICIRCLOG-107 …
> UICIRCLOG-107 Add view permission to Circulation log

- CHANGELOG.md
- src/CirculationLogList/CirculationLogEventActions/CirculationLogEventActions.js
https://issues.folio.org/browse/UICIRCLOG-109 …
> UICIRCLOG-109 Update circ log Actions ellipses UX

- CHANGELOG.md
- package.json
bump stripes to 8.0.0 for Orchid/2023-R1
Issue: https://issues.folio.org/browse/UICIRCLOG-111
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team dependencies …
> UICIRCLOG - bump stripes to 8.0.0 for Orchid/2023-R1

- CHANGELOG.md
- package.json
- src/CirculationLogList/CirculationLogListActions/useCirculationLogExport.js
- src/CirculationLogList/CirculationLogListActions/useCirculationLogExport.test.js
- src/CirculationLogList/constants.js
https://issues.folio.org/browse/UIEXPMGR-65 …
> Download refactoring to support /download endpoint

- CHANGELOG.md
- src/CirculationLogList/constants.js
Implement EXACT search for item barcode in circulation log	
Update query that goes through url
Note: There were some db level changes that had happened - handled through tickets - https://issues.folio.org/browse/MODAUD-155 and https://issues.folio.org/browse/MODAUD-159
Fetch an item with given barcode from 10 Million records 
Before -
After
https://issues.folio.org/browse/UICIRCLOG-115
- …
> UICIRCLOG-115 - Implement EXACT search for item barcode in circulation log

- CHANGELOG.md
- src/CirculationLogList/CirculationLogList.js
- src/CirculationLogList/CirculationLogListContainer.js
- src/CirculationLogList/markOldPatronInfoAsSuperseded.js
- src/CirculationLogList/markOldPatronInfoAsSuperseded.test.js
- src/hooks/useCirculationLog.js
https://issues.folio.org/browse/UICIRCLOG-130
UI-CIRCLOG-130. Display of patron info marked as (SUPERSEDED)
> UI-CIRCLOG-130: Display of patron info marked as SUPERSEDED

- .github/workflows/build-npm-release.yml
- .github/workflows/build-npm.yml
- CHANGELOG.md
- package.json
[UICIRCLOG-131](https://issues.folio.org/browse/UICIRCLOG-131) - Update Node.js to v18 in GitHub Actions
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of intermodule and inter-team …
> UICIRCLOG-131 - Update Node.js to v18 in GitHub Actions

- CHANGELOG.md
- package.json
update file to reflect release 4.0.1
While it's helpful for reviewers to help identify …
> UICIRCLOG-142 - update file to reflect release 4.0.1

- CHANGELOG.md
- src/CirculationLogList/CirculationLogEventItems/CirculationLogEventItem.js
- src/CirculationLogList/constants.js
- src/CirculationLogList/utils.hollow.test.js
- src/CirculationLogList/utils.js
[UICIRCLOG-140](https://issues.folio.org/browse/UICIRCLOG-140) - [DCB] Disable item barcode link
Display item barcode as text when item in the log event is virtual which means item's instance id is equal to DCB_INSTANCE_ID and holdingId is equal to DCB_HOLDINGS_RECORD_ID
Ideally all of the PRs involved in breaking changes would be merged in the same day to …
> UICIRCLOG-140 - Disable item barcode link for virtual items, in circulation log list.

- .github/workflows/build-npm-release.yml
- .github/workflows/build-npm.yml
- CHANGELOG.md
[UICIRC-159](https://folio-org.atlassian.net/browse/UICIRCLOG-159)
While it's helpful for …
> UICIRCLOG-159 - upgrade 'actions/upload-artifact' version to v4

- CHANGELOG.md
- package.json
- src/CirculationLogList/utils.hollow.test.js
[UICIRCLOG-165](https://folio-org.atlassian.net/browse/UICIRCLOG-165) - Bump "@folio/stripes-acq-components" version to v6.00
[UICIRCLOG-141](https://folio-org.atlassian.net/browse/UICIRCLOG-141) - fix lint configuration
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment. …
> UICIRCLOG-165 - Bump "@folio/stripes-acq-components" version to v6.00 and also fix lint config and most of the lint issues

- CHANGELOG.md
- package.json
This PR intends to make a patch release for Ramsons …
> UI-CIRCLOG-168 Ramsons patch release

- CHANGELOG.md
- package.json
update changelog and package.json after 5.0.1 release
While it's helpful for reviewers to …
> update changelog and package.json after 5.0.1 release

- CHANGELOG.md
- src/CirculationLogList/CirculationLogEventActions/CirculationLogEventActions.js
- src/CirculationLogList/CirculationLogList.js
- src/CirculationLogList/CirculationLogListFilter/CirculationLogListFilter.js
[UICIRCLOG-155](https://folio-org.atlassian.net/browse/UICIRCLOG-155) - React v19: refactor away from default props for functional components
Ideally all of the PRs involved in breaking changes would be merged in the same day to avoid breaking the folio-testing environment.  Communication is paramount if that is to be achieved, especially as the number of …
> UICIRCLOG-155 - React v19: refactor away from default props for functional components

- CHANGELOG.md
- package.json
https://folio-org.atlassian.net/browse/UICIRCLOG-170; https://folio-org.atlassian.net/browse/UICIRCLOG-171
> UICIRCLOG-170, UICIRCLOG-171: migrate stripes-* deps; react-intl to v7

- CHANGELOG.md
- package.json
https://folio-org.atlassian.net/browse/UICIRCLOG-175
> UICIRCLOG-175: Bump @folio/stripes-acq-components to 7.0.0
